# Generated by Django 3.1 on 2020-10-02 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_pick', models.ImageField(null=True, upload_to='UsrPost/post_img')),
                ('subject', models.CharField(max_length=75)),
                ('msg', models.TextField(blank=True, null=True)),
                ('creat_date', models.DateTimeField(auto_now_add=True)),
                ('uploded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.normalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NormalPostComment',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField()),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('Comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment_by', to='Account.normalprofile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NormPro.normalpostcomment')),
                ('post_is', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_is', to='NormPro.normalposts')),
            ],
        ),
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.ManyToManyField(related_name='NormalPost_Like_by', to=settings.AUTH_USER_MODEL)),
                ('normal_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='NormPro.normalposts')),
            ],
        ),
    ]
