# Generated by Django 3.1 on 2020-10-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=18)),
                ('longitude', models.FloatField(max_length=18)),
                ('pop_up_text', models.CharField(max_length=45)),
            ],
        ),
    ]
